ALTER TABLE users
ADD COLUMN profile INTEGER DEFAULT 0,
ADD COLUMN telegram_id BIGINT DEFAULT 0,
ADD COLUMN telegram_chat BIGINT DEFAULT 0,
ADD COLUMN n_movie INTEGER DEFAULT 0,
ADD COLUMN n_tv INTEGER DEFAULT 0,
ADD COLUMN n_voice INTEGER DEFAULT 0,
ADD COLUMN premium INTEGER DEFAULT 0,
ADD COLUMN backup INTEGER DEFAULT 0,
ADD COLUMN permission INTEGER DEFAULT 0,
ADD COLUMN bet VARCHAR(255) DEFAULT '',
ADD COLUMN payout INTEGER DEFAULT 0; 